### ISSUE TITLE
MapR 6.1, MEP6 and JDK

### ISSUE THREAD

**Issue by dazzla76** [JohnOmernik/maprssss#1]
Hi John,

This looks really good, thank you for putting it together.

Do you have any idea how much work it would be to uplift this for MapR 6.1? i'm guessing the streamsets version would need to be changed in parallel.

In addition, did you use oracle JDK for any particular reason or could i switch to openjdk if needed?

Regards

**Comment by JohnOmernik** [comment]
I think I based Oracle JDK off another container I found. Now that I think about it, I am guessing I don't have to include the JDK install, the MapR PACC should have it in there... I need to research that. As to the MapR Version, Streamsets doesn't support the 6.1/MEP6 combo yet. So I have it on the most recently supported verison (MapR 6.0.1/MEP5).

**Comment by dazzla76** [comment]
Thank you,

Fair enough on Streamsets compatibility.  I guess 6.0/MEP5 should be ok against 6.1 anyway just for testing.
